// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "BfM Support",
            "url": "https://github.com/toolsascode/bfm"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "https://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Checks the health status of the API",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "Healthy",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "503": {
                        "description": "Unhealthy",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/migrations": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Lists all migrations with optional filtering",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "migrations"
                ],
                "summary": "List migrations",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Schema filter",
                        "name": "schema",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Table filter",
                        "name": "table",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Connection filter",
                        "name": "connection",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Backend filter",
                        "name": "backend",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Status filter",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Version filter",
                        "name": "version",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/dto.MigrationListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/migrations/down": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Executes down migrations to rollback a specific migration",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "migrations"
                ],
                "summary": "Execute down migrations (rollback)",
                "parameters": [
                    {
                        "description": "Rollback request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.MigrateDownRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/dto.MigrateResponse"
                        }
                    },
                    "206": {
                        "description": "Partial success",
                        "schema": {
                            "$ref": "#/definitions/dto.MigrateResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/migrations/executions/recent": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Gets recent execution records across all migrations",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "migrations"
                ],
                "summary": "Get recent executions",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Limit number of results",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/migrations/reindex": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Reindexes all migration files and synchronizes with database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "migrations"
                ],
                "summary": "Reindex migrations",
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/dto.ReindexResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/migrations/up": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Executes migrations based on the provided target and connection",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "migrations"
                ],
                "summary": "Execute up migrations",
                "parameters": [
                    {
                        "description": "Migration request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.MigrateUpRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/dto.MigrateResponse"
                        }
                    },
                    "206": {
                        "description": "Partial success",
                        "schema": {
                            "$ref": "#/definitions/dto.MigrateResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/migrations/{id}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Gets detailed information about a specific migration",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "migrations"
                ],
                "summary": "Get migration details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Migration ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/dto.MigrationDetailResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Migration not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/migrations/{id}/executions": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Gets all execution records for a specific migration",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "migrations"
                ],
                "summary": "Get migration executions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Migration ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/migrations/{id}/history": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Gets the execution history for a specific migration including rollbacks",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "migrations"
                ],
                "summary": "Get migration history",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Migration ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Migration not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/migrations/{id}/rollback": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Rolls back a specific migration",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "migrations"
                ],
                "summary": "Rollback migration",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Migration ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Rollback request",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/dto.RollbackRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Migration not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/migrations/{id}/status": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Gets the current status of a specific migration",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "migrations"
                ],
                "summary": "Get migration status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Migration ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.DependencyResponse": {
            "type": "object",
            "properties": {
                "connection": {
                    "type": "string"
                },
                "requires_schema": {
                    "type": "string"
                },
                "requires_table": {
                    "type": "string"
                },
                "schema": {
                    "type": "string"
                },
                "target": {
                    "type": "string"
                },
                "target_type": {
                    "type": "string"
                }
            }
        },
        "dto.MigrateDownRequest": {
            "type": "object",
            "required": [
                "migration_id"
            ],
            "properties": {
                "dry_run": {
                    "type": "boolean"
                },
                "ignore_dependencies": {
                    "type": "boolean"
                },
                "migration_id": {
                    "type": "string"
                },
                "schemas": {
                    "description": "Array for dynamic schemas",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "dto.MigrateResponse": {
            "type": "object",
            "properties": {
                "applied": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "errors": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "skipped": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "dto.MigrateUpRequest": {
            "type": "object",
            "required": [
                "connection"
            ],
            "properties": {
                "connection": {
                    "type": "string"
                },
                "dry_run": {
                    "type": "boolean"
                },
                "ignore_dependencies": {
                    "type": "boolean"
                },
                "schemas": {
                    "description": "Array for dynamic schemas",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "target": {
                    "$ref": "#/definitions/registry.MigrationTarget"
                }
            }
        },
        "dto.MigrationDetailResponse": {
            "type": "object",
            "properties": {
                "applied": {
                    "type": "boolean"
                },
                "backend": {
                    "type": "string"
                },
                "connection": {
                    "type": "string"
                },
                "dependencies": {
                    "description": "List of migration names this migration depends on (backward compatibility)",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "down_sql": {
                    "description": "Contains SQL for SQL backends or JSON for NoSQL backends",
                    "type": "string"
                },
                "migration_id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "schema": {
                    "type": "string"
                },
                "structured_dependencies": {
                    "description": "Structured dependencies with validation requirements",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.DependencyResponse"
                    }
                },
                "table": {
                    "type": "string"
                },
                "up_sql": {
                    "description": "Contains SQL for SQL backends or JSON for NoSQL backends",
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "dto.MigrationListItem": {
            "type": "object",
            "properties": {
                "applied": {
                    "type": "boolean"
                },
                "applied_at": {
                    "type": "string"
                },
                "backend": {
                    "type": "string"
                },
                "connection": {
                    "type": "string"
                },
                "error_message": {
                    "type": "string"
                },
                "migration_id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "schema": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "table": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "dto.MigrationListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.MigrationListItem"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dto.ReindexResponse": {
            "type": "object",
            "properties": {
                "added": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "removed": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "total": {
                    "type": "integer"
                },
                "updated": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "dto.RollbackRequest": {
            "type": "object",
            "properties": {
                "schemas": {
                    "description": "Array for dynamic schemas",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "registry.MigrationTarget": {
            "type": "object",
            "properties": {
                "backend": {
                    "description": "Backend type filter",
                    "type": "string"
                },
                "connection": {
                    "description": "Connection name filter",
                    "type": "string"
                },
                "schema": {
                    "description": "Schema filter (optional)",
                    "type": "string"
                },
                "tables": {
                    "description": "Table filters (optional, empty = all)",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "version": {
                    "description": "Version filter (optional, empty = latest)",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "description": "API token authentication. Include the token in the Authorization header: Authorization: Bearer {BFM_API_TOKEN}",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.3.0",
	Host:             "localhost:7070",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Backend For Migrations (BfM) API",
	Description:      "BfM is a comprehensive database migration system that supports multiple backends\n(PostgreSQL, GreptimeDB, Etcd) with HTTP and Protobuf APIs.\n\nThis API allows you to:\n- Execute up migrations\n- Execute down migrations (rollback)\n- List migrations with filtering\n- Get migration details and status\n- View migration history\n- Check system health",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
