version: 2
project_name: bfm

# Build configuration
builds:
  - id: bfm
    dir: api
    main: ./cmd/cli
    binary: bfm
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    hooks:
      pre: |
        # Install protoc if not available
        if ! command -v protoc &> /dev/null; then
          if [[ "$OSTYPE" == "linux-gnu"* ]]; then
            sudo apt-get update && sudo apt-get install -y protobuf-compiler || true
          elif [[ "$OSTYPE" == "darwin"* ]]; then
            brew install protobuf || true
          fi
        fi
        # Install Go protobuf plugins
        go install google.golang.org/protobuf/cmd/protoc-gen-go@latest || true
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest || true
        # Generate protobuf code
        cd internal/api/protobuf && ./generate.sh || true
        cd ../../..

# Archive configuration
# See: https://goreleaser.com/customization/archive/
archives:
  - id: default
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
    # Override format for Windows to use zip
    format_overrides:
      - goos: windows
        formats:
          - zip

# Checksums
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

signs:
  - artifacts: checksum
    cmd: gpg2
    args:
      - "--batch"
      - "-u"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^test\\("
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy

# GitHub release configuration
release:
  github:
    owner: toolsascode
    name: bfm
  mode: replace
  header: |
    ## What's Changed
    Full Changelog: https://github.com/toolsascode/bfm/compare/{{ .PreviousTag }}...{{ .Tag }}

# https://github.com/settings/tokens/new?scopes=gist,public_repo&description=Homebrew
# Homebrew Cask configuration (migrated from deprecated brews)
# See: https://goreleaser.com/customization/homebrew_casks/
homebrew_casks:
  - name: bfm
    # Binary name inside the cask
    binaries:
      - bfm
    # Repository where the cask will be published
    repository:
      owner: toolsascode
      name: homebrew-tap
    # Cask metadata
    homepage: "https://github.com/toolsascode/bfm"
    description: "BfM - Backend for Migrations CLI"
    license: "MIT"
    # Post-install hook to remove quarantine attribute (required for unsigned binaries)
    # This allows the binary to run on macOS without code signing/notarization
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bfm"]
          end

scoops:
  - name: bfm
    repository:
      owner: toolsascode
      name: scoop-bucket
    homepage: "https://github.com/toolsascode/bfm"
    description: "BfM - Backend for Migrations CLI"
    license: "MIT"
    persist:
      - "config"
