// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.3
// source: migration.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MigrationTarget specifies which migrations to execute
type MigrationTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Backend       string                 `protobuf:"bytes,1,opt,name=backend,proto3" json:"backend,omitempty"`       // Backend type filter
	Schema        string                 `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"`         // Schema filter (optional)
	Tables        []string               `protobuf:"bytes,3,rep,name=tables,proto3" json:"tables,omitempty"`         // Table filters (optional, empty = all)
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`       // Version filter (optional, empty = latest)
	Connection    string                 `protobuf:"bytes,5,opt,name=connection,proto3" json:"connection,omitempty"` // Connection name filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrationTarget) Reset() {
	*x = MigrationTarget{}
	mi := &file_migration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrationTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationTarget) ProtoMessage() {}

func (x *MigrationTarget) ProtoReflect() protoreflect.Message {
	mi := &file_migration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationTarget.ProtoReflect.Descriptor instead.
func (*MigrationTarget) Descriptor() ([]byte, []int) {
	return file_migration_proto_rawDescGZIP(), []int{0}
}

func (x *MigrationTarget) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

func (x *MigrationTarget) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *MigrationTarget) GetTables() []string {
	if x != nil {
		return x.Tables
	}
	return nil
}

func (x *MigrationTarget) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *MigrationTarget) GetConnection() string {
	if x != nil {
		return x.Connection
	}
	return ""
}

// MigrateRequest represents a migration request
type MigrateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        *MigrationTarget       `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Connection    string                 `protobuf:"bytes,2,opt,name=connection,proto3" json:"connection,omitempty"`
	Schema        string                 `protobuf:"bytes,3,opt,name=schema,proto3" json:"schema,omitempty"`                           // Optional
	SchemaName    string                 `protobuf:"bytes,4,opt,name=schema_name,json=schemaName,proto3" json:"schema_name,omitempty"` // For dynamic schemas
	DryRun        bool                   `protobuf:"varint,5,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`            // Optional, default false
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrateRequest) Reset() {
	*x = MigrateRequest{}
	mi := &file_migration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrateRequest) ProtoMessage() {}

func (x *MigrateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_migration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrateRequest.ProtoReflect.Descriptor instead.
func (*MigrateRequest) Descriptor() ([]byte, []int) {
	return file_migration_proto_rawDescGZIP(), []int{1}
}

func (x *MigrateRequest) GetTarget() *MigrationTarget {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *MigrateRequest) GetConnection() string {
	if x != nil {
		return x.Connection
	}
	return ""
}

func (x *MigrateRequest) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *MigrateRequest) GetSchemaName() string {
	if x != nil {
		return x.SchemaName
	}
	return ""
}

func (x *MigrateRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

// MigrateResponse represents a migration response
type MigrateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Applied       []string               `protobuf:"bytes,2,rep,name=applied,proto3" json:"applied,omitempty"`
	Skipped       []string               `protobuf:"bytes,3,rep,name=skipped,proto3" json:"skipped,omitempty"`
	Errors        []string               `protobuf:"bytes,4,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrateResponse) Reset() {
	*x = MigrateResponse{}
	mi := &file_migration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrateResponse) ProtoMessage() {}

func (x *MigrateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_migration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrateResponse.ProtoReflect.Descriptor instead.
func (*MigrateResponse) Descriptor() ([]byte, []int) {
	return file_migration_proto_rawDescGZIP(), []int{2}
}

func (x *MigrateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MigrateResponse) GetApplied() []string {
	if x != nil {
		return x.Applied
	}
	return nil
}

func (x *MigrateResponse) GetSkipped() []string {
	if x != nil {
		return x.Skipped
	}
	return nil
}

func (x *MigrateResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

// MigrateProgress represents progress updates during migration
type MigrateProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MigrationId   string                 `protobuf:"bytes,1,opt,name=migration_id,json=migrationId,proto3" json:"migration_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "pending", "running", "success", "failed"
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Progress      int32                  `protobuf:"varint,4,opt,name=progress,proto3" json:"progress,omitempty"` // 0-100
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrateProgress) Reset() {
	*x = MigrateProgress{}
	mi := &file_migration_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrateProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrateProgress) ProtoMessage() {}

func (x *MigrateProgress) ProtoReflect() protoreflect.Message {
	mi := &file_migration_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrateProgress.ProtoReflect.Descriptor instead.
func (*MigrateProgress) Descriptor() ([]byte, []int) {
	return file_migration_proto_rawDescGZIP(), []int{3}
}

func (x *MigrateProgress) GetMigrationId() string {
	if x != nil {
		return x.MigrationId
	}
	return ""
}

func (x *MigrateProgress) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MigrateProgress) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MigrateProgress) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

var File_migration_proto protoreflect.FileDescriptor

const file_migration_proto_rawDesc = "" +
	"\n" +
	"\x0fmigration.proto\x12\tmigration\"\x95\x01\n" +
	"\x0fMigrationTarget\x12\x18\n" +
	"\abackend\x18\x01 \x01(\tR\abackend\x12\x16\n" +
	"\x06schema\x18\x02 \x01(\tR\x06schema\x12\x16\n" +
	"\x06tables\x18\x03 \x03(\tR\x06tables\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x1e\n" +
	"\n" +
	"connection\x18\x05 \x01(\tR\n" +
	"connection\"\xb6\x01\n" +
	"\x0eMigrateRequest\x122\n" +
	"\x06target\x18\x01 \x01(\v2\x1a.migration.MigrationTargetR\x06target\x12\x1e\n" +
	"\n" +
	"connection\x18\x02 \x01(\tR\n" +
	"connection\x12\x16\n" +
	"\x06schema\x18\x03 \x01(\tR\x06schema\x12\x1f\n" +
	"\vschema_name\x18\x04 \x01(\tR\n" +
	"schemaName\x12\x17\n" +
	"\adry_run\x18\x05 \x01(\bR\x06dryRun\"w\n" +
	"\x0fMigrateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\aapplied\x18\x02 \x03(\tR\aapplied\x12\x18\n" +
	"\askipped\x18\x03 \x03(\tR\askipped\x12\x16\n" +
	"\x06errors\x18\x04 \x03(\tR\x06errors\"\x82\x01\n" +
	"\x0fMigrateProgress\x12!\n" +
	"\fmigration_id\x18\x01 \x01(\tR\vmigrationId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1a\n" +
	"\bprogress\x18\x04 \x01(\x05R\bprogress2\x9e\x01\n" +
	"\x10MigrationService\x12@\n" +
	"\aMigrate\x12\x19.migration.MigrateRequest\x1a\x1a.migration.MigrateResponse\x12H\n" +
	"\rStreamMigrate\x12\x19.migration.MigrateRequest\x1a\x1a.migration.MigrateProgress0\x01B\x1fZ\x1dbfm/api/internal/api/protobufb\x06proto3"

var (
	file_migration_proto_rawDescOnce sync.Once
	file_migration_proto_rawDescData []byte
)

func file_migration_proto_rawDescGZIP() []byte {
	file_migration_proto_rawDescOnce.Do(func() {
		file_migration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_migration_proto_rawDesc), len(file_migration_proto_rawDesc)))
	})
	return file_migration_proto_rawDescData
}

var file_migration_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_migration_proto_goTypes = []any{
	(*MigrationTarget)(nil), // 0: migration.MigrationTarget
	(*MigrateRequest)(nil),  // 1: migration.MigrateRequest
	(*MigrateResponse)(nil), // 2: migration.MigrateResponse
	(*MigrateProgress)(nil), // 3: migration.MigrateProgress
}
var file_migration_proto_depIdxs = []int32{
	0, // 0: migration.MigrateRequest.target:type_name -> migration.MigrationTarget
	1, // 1: migration.MigrationService.Migrate:input_type -> migration.MigrateRequest
	1, // 2: migration.MigrationService.StreamMigrate:input_type -> migration.MigrateRequest
	2, // 3: migration.MigrationService.Migrate:output_type -> migration.MigrateResponse
	3, // 4: migration.MigrationService.StreamMigrate:output_type -> migration.MigrateProgress
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_migration_proto_init() }
func file_migration_proto_init() {
	if File_migration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_migration_proto_rawDesc), len(file_migration_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_migration_proto_goTypes,
		DependencyIndexes: file_migration_proto_depIdxs,
		MessageInfos:      file_migration_proto_msgTypes,
	}.Build()
	File_migration_proto = out.File
	file_migration_proto_goTypes = nil
	file_migration_proto_depIdxs = nil
}
